name: SignPortal
api: [1.10.0,1.12.0,2.0.0] #Not compatible with previous versions due to usage of SignChangeEvent
version: 1.1.1
load: POSTWORLD
main: leonchang99\SignPortal\Main
author: 99leonchang
website: https://github.com/99leonchang/SignPortal

commands:
 generate:
  description: Generate new world (testing only)
  usage: "Usage: /generate <worldname>"
  permission: signportal.command.generate

permissions:
 signportal.command.generate:
  description: "Allows the user to run the generate command"
  default: op
